# Generated by Django 2.2.4 on 2020-05-25 08:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hello',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
