# Generated by Django 2.2.4 on 2020-07-11 08:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='method',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
