# Generated by Django 2.2.4 on 2020-05-25 08:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0002_player_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hello',
        ),
        migrations.AddField(
            model_name='player',
            name='are_you_ok',
            field=otree.db.models.BooleanField(choices=[['很好', True], ['還好', False]], null=True),
        ),
    ]
