# Generated by Django 2.2.4 on 2020-07-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0002_player_treatment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='treatment_method',
        ),
    ]
