# Generated by Django 2.2.4 on 2020-07-20 17:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0002_player_treatment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='treatmennt',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
