# Generated by Django 2.2.4 on 2020-07-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0002_player_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='method',
        ),
    ]
