# Generated by Django 2.2.4 on 2020-07-20 17:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0003_player_treatmennt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='treatmennt',
        ),
        migrations.AddField(
            model_name='player',
            name='treatment',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
