# Generated by Django 2.2.4 on 2020-07-13 12:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0003_remove_player_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='treatment_rate',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
