# Generated by Django 2.2.4 on 2020-07-13 09:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0003_remove_player_treatment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='treatment_method',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
