# Generated by Django 2.2.4 on 2020-05-25 08:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0004_auto_20200525_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='are_you_ok',
            field=otree.db.models.BooleanField(choices=[[True, '很好'], [False, '還好']], null=True, verbose_name='你今天好嗎？'),
        ),
    ]
