# Generated by Django 2.2.4 on 2020-07-13 13:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing1', '0006_auto_20200713_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='treatment_rate',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
